import{i as l,S as u}from"./assets/vendor-8c59ed88.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&n(o)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();function p(i){return fetch(`https://pixabay.com/api/?key=43859237-c6386bdcccc66f068a9509366&q=${i}&image_type=photo&orientation=horizontal&safesearch=true`).then(n=>{if(!n.ok)throw new Error(n.statusText);return n.json()})}function d(i){return i.map(({downloads:r,webformatURL:s,largeImageURL:n,tags:e,likes:t,views:o,comments:c})=>`
    <a class="gallery-link" href="${n}">
    <img class="gallery-image" src="${s}" alt="${e}"/>
    <div class="gallery-list">
    <div class="gallery-item"><b>Likes</b> <span>${t}</span></div>
    <div class="gallery-item"><b>Views</b> <span>${o}</span></div>
    <div class="gallery-item"><b>Comments</b> <span>${c}</span></div>
    <div class="gallery-item"><b>Downloads</b> <span>${r}</span></div>
    </div></a>
      `).join("")}const f=document.querySelector(".submit-form"),a=document.querySelector(".gallery");f.addEventListener("submit",m);function m(i){i.preventDefault(),a.innerHTML='<span class="loader"></span>';const r=i.currentTarget.elements.search.value;r.length!==0&&p(r).then(s=>{if(s.hits.length===0){l.show({message:" Sorry, there are no images matching your search query. Please try again!",color:"#EF4040",position:"topRight",messageColor:"white",messageSize:"5px",timeout:2e3,padding:"20px",gap:"8px",borderRadius:"4px"}),a.innerHTML="";return}a.innerHTML=d(s.hits),g()}).catch(s=>console.log(s))}function g(){new u(".gallery a",{captionsDelay:250,captionPosition:"bottom"}).refresh()}
//# sourceMappingURL=commonHelpers.js.map
